
{% set version = "1.18.1" %}

package:
  name: geopy
  version: {{ version }}

source:
  url: https://github.com/geopy/geopy/archive/{{ version }}.tar.gz
  sha256: bf332d9c3cfe2eac1ae5014df2b05da832ebe3b66ebb0c9e0baaafaebc767dcc

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - geographiclib <2,>=1.49

test:
  imports:
    - geopy
    - geopy.geocoders

about:
  home: https://github.com/geopy/geopy
  license: MIT
  license_file: LICENSE
  summary: 'Python Geocoding Toolbox.'

extra:
  recipe-maintainers:
    - ocefpaf
    - pmlandwehr
