{% set version = "1.12.0" %}

package:
  name: geopy
  version: {{ version }}

source:
  fn: geopy-{{ version }}.tar.gz
  url: https://github.com/geopy/geopy/archive/{{ version }}.tar.gz
  sha256: 03ad92f8fc7b953f01fcb66d14a5b7978cbde76c75ad73cdb84a6c1fa27f5e1f

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - geopy
    - geopy.geocoders

about:
  home: https://github.com/geopy/geopy
  license: MIT
  summary: 'Python Geocoding Toolbox.'

extra:
  recipe-maintainers:
    - ocefpaf
    - pmlandwehr
