{% set name = "geopy" %}
{% set version = "2.4.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 50283d8e7ad07d89be5cb027338c6365a32044df3ae2556ad3f52f4840b3d0d1

build:
  skip: true  # [py<37]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vvv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - geographiclib >=1.52,<3
  run_constrained:
    - urllib >=1.24.2
    - requests >=2.16.2

test:
  source_files:
    - test
  imports:
    - geopy
    - geopy.geocoders
    - geopy.extra
  commands:
    - pip check
    - pytest test -v
  requires:
    - pip
    - pytest

about:
  home: https://github.com/geopy/geopy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python Geocoding Toolbox.
  description: |
    geopy is a Python client for several popular geocoding web services.
    geopy makes it easy for Python developers to locate the coordinates of addresses,
    cities, countries, and landmarks across the globe using third-party geocoders and
    other data sources. geopy includes geocoder classes for the OpenStreetMap Nominatim,
    Google Geocoding API (V3), and many other geocoding services. The full list is available
    on the Geocoders doc section. Geocoder classes are located in geopy.geocoders.
  doc_url: https://geopy.readthedocs.io/en/latest/
  dev_url: https://github.com/geopy/geopy

extra:
  recipe-maintainers:
    - ocefpaf
    - pmlandwehr
