
{% set version = "1.13.0" %}

package:
  name: geopy
  version: {{ version }}

source:
  url: https://github.com/geopy/geopy/archive/{{ version }}.tar.gz
  sha256: e8714db6e8100a2c7a05e56aeefb53172aa67b55ee3b859e05151bda958c01f6

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - geopy
    - geopy.distance.geodesic
    - geopy.geocoders

about:
  home: https://github.com/geopy/geopy
  license: MIT
  license_file: LICENSE
  summary: 'Python Geocoding Toolbox.'

extra:
  recipe-maintainers:
    - ocefpaf
    - pmlandwehr
