{% set version = "1.22.0" %}

package:
  name: geopy
  version: {{ version }}

source:
  url: https://github.com/geopy/geopy/archive/{{ version }}.tar.gz
  sha256: ab5d13de571055ee70c76b602a886bad8276aa3cee5037bb1a65e01202e84fd4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - geographiclib <2,>=1.49

test:
  imports:
    - geopy
    - geopy.geocoders

about:
  home: https://github.com/geopy/geopy
  license: MIT
  license_file: LICENSE
  summary: Python Geocoding Toolbox.

extra:
  recipe-maintainers:
    - ocefpaf
    - pmlandwehr
