{% set version = "2.0.0" %}

package:
  name: geopy
  version: {{ version }}

source:
  url: https://github.com/geopy/geopy/archive/{{ version }}.tar.gz
  sha256: eae8713341b8bb875ae2a5b9be145888e2ea93b0bf34b3de7d7cef9f283fc764

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - geographiclib <2,>=1.49

test:
  imports:
    - geopy
    - geopy.geocoders
    - geopy.extra
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/geopy/geopy
  license: MIT
  license_file: LICENSE
  summary: Python Geocoding Toolbox.

extra:
  recipe-maintainers:
    - ocefpaf
    - pmlandwehr
