{% set version = "2.3.0" %}

package:
  name: geopy
  version: {{ version }}

source:
  url: https://github.com/geopy/geopy/archive/{{ version }}.tar.gz
  sha256: 51745ba5497306ce26e71b794bef6052b17eb8dcc517d27e1aa030ac93863e1a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - geographiclib <2,>=1.49

test:
  imports:
    - geopy
    - geopy.geocoders
    - geopy.extra
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/geopy/geopy
  license: MIT
  license_file: LICENSE
  summary: Python Geocoding Toolbox.

extra:
  recipe-maintainers:
    - ocefpaf
    - pmlandwehr
