
{% set version = "1.17.0" %}

package:
  name: geopy
  version: {{ version }}

source:
  url: https://github.com/geopy/geopy/archive/{{ version }}.tar.gz
  sha256: 928d431ea2f0151e3b1004874afd85b3e43063a9f029dae68d313a9db7d36109

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - geographiclib <2,>=1.49

test:
  imports:
    - geopy
    - geopy.geocoders

about:
  home: https://github.com/geopy/geopy
  license: MIT
  license_file: LICENSE
  summary: 'Python Geocoding Toolbox.'

extra:
  recipe-maintainers:
    - ocefpaf
    - pmlandwehr
