travis:
  secure:
    BINSTAR_TOKEN: a1Krq2vkVMW3fScsNmqB3eJXY3zbgvUOL/GG+e08Itv9fmmkI8UAE9ohil0SsiAi03Egr2tzH9q/xRCaqc9PD9E4qFXTNb8uDUMfoZ1UjP01tLqianxqEi5J6R417+LkRm/ghKJPlJ2ESf5oDyiDg2n1j30dGriAMZRoTrEkxwJxFohQInyTrkObVX068pgulQ9rENmQdepSEut/HMm+avpAs7+8uvkS8+2XJEuaUCbXZFgEZK5f5pjBzi2t5BTUiPLFjz+ntoSx9DW7dcBkqSzuTEVcfjpk87Mw4RBi1ZAsc0Y9M/IwEvUNxLNFFwRmpXcgkqT5mio/j/Wyw6LJ+W91m5hzCJ5x1qyVGD+ORyRnvYV2hawsdY8QXoZIKS2s+7jm96WmuyxvymBnAJ2lFp6dfZcBpk5kxYpxFYiIiuN8d+WUnRvFXh3w4sIZTmKDxIPMBNoVFwvOM0wqakqHUUBqEZHobstqhALnysnRKb0P2l5kKzr9f8Erq969+uqpEsAYVKc25Mp5/LPbyzz87O9OC6Jyxp+bbFOSD0ZqVGl92T1qv/RQdngkKIeZuMibZRycY51LgdzPlJtHz9PD6601Vdow+XXxXQxnJGdgb25u9XryhBontbNcSqIC2LXukXFcYqgY5+y0uq/5TN9SzcAbmX0fJbYku8EWCVE1390=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
