travis:
  secure:
    BINSTAR_TOKEN: RZM/n46eIkGxitXW8vWavFR6MWx4SNcySAHNllYIJsg/uYdRJdpYdD5n+igHkkue/Yd2Hvu+6WqV6Ip+NjIH1Ldf0JEh9iAdMKt25lS+YPooG+JATbCwjGsmbKPvUwCfGaXXI7ItkWbu927eGjQb1MLsj/n4v5xYdRI70KS+bL1a4K8ow4QP6NQ6ByZ5zUb/FHGhnEXc+7z5mH3f3eJ9/3eaFBNi5CH1U8mLkcKozEomrh04/SmMCXi2w9V+PB1whOJMLUhuZqQXb4iiZyTYBsxcqZBuR6hYO6kmcOabqKSBpXJRcBDMixHJqiizLo3aPT0xfoPlyO92WesshZyhTwcogs6O8Pf49hut4HzUbgAXWvKycPj+EedyTioz/Z2Bcim5AQ+NKSQwFPKVcmQA8r+Yp7Bcxq1hNWkypANFhSETqTZ3csT235d50fbLAa1hQzIJ2u8disXPi8B8dRzMsvYo2NhwMCuoxvVxs9RgZUy6Jz1NZqewZxDgGob+FfE1iBucBKwZ3Wr1Xcbs37W+fNnTKzVFhxZgEXMZLoiGZEEBkugdZqITBM9Q5FJ6oyc2hvB2t5wkxlblRtHw2WzJb/QsqXyceYsfSESxnZgOP+v/ICf9EObsEysl/U67RKJgGLRBNh3XfITGfbadt7/PtJYwyaHyfaeRuGSvXivkx6k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
