travis:
  secure:
    BINSTAR_TOKEN: b/8O6NZtjgIAfaPwoCmACaPpX8ULGNUXscdORCFmGGMD9EgdkSMhCH+/6zOGPnwpSmFNAtKlxjpwo/DIiaa2UhwSzVaf0Y2YJqMrCGmg6XnxOMIzxZlJ/fFIHG3P7xmNzqcHF+uEHohkGjC4a8Hm3idnWUnEZBfGBdDibQPQ2LCwFrN03RLeqAZLQOUrnJ2bjsp2xx53/rsoupfyQPHpOMDET+C8AIAIbiMfqOUBHF3y9j5aXKcaalKMIm4LAGomJzNFKQ5OPvLPK61wM4aP7eUhJq7oIXAfCsdh4w84Cwzx19rDRAaxEtkpKU4eYISGhqeOtOL9rnkyzk784VNp5PAGSLL37Xv/tT/hZ0rCmjY43rgxxFL08i8t0Osx1No0EGXqNakTMAkT2cav1lBrZL3ruj8NC30jAhgjkXE2Z4IAmjlSmpx8ive2xFX3jYQnRrJRpxorccCE8oF+vDXtnN4v7nNxPijuLVIO7gMH7iyDNFoUd5dNpun8pUuqPy2uuAJlaMjKR4o7GbJEwBFs2VpTuOhw9LE79tyL2cXlPptN3PumULnzAyLbzk/4kcbvnk7KpihWdXXxJoTarjiz/yk7mLIS8FoZgmfkGA2Epeq3DmFKyV2kmTldwpVvQASQpMfps6/qaWFzXpZIrLycUbsIct7H3AiTlbKcKDROrNc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
